image: openjdk:8
stages:
  - build
  - test
build:
  stage: build
  script:
    - gradle clean build --stacktrace
test:
  image: testvagrant/seleniumimage
  stage: test
  script:
    - gradle runTests --stacktrace

  only:
    - driverfactory
    - develop