image: openjdk:8
stages:
  - build
  - test
build:
  stage: build
  script:
    - gradle clean build
test:
  image: testvagrant/seleniumimage
  stage: test
  script:
    - gradle runTests
  artifacts:
    when: always
    paths:
      - ./build/myshopify/*
  only:
    - develop